import './global.css';
import 'overlayscrollbars/overlayscrollbars.css';
import { Metadata } from 'next';
import { AppInitConfig } from '@config';

export const metadata: Metadata = {
  title: 'Welcome to fe-shop',
  description: 'Generated by create-nx-workspace',
};

const RootLayout: FCC = ({ children }) => {
  return (
    <html lang="en" data-overlayscrollbars-initialize>
      <body data-overlayscrollbars-initialize>
        <AppInitConfig />
        {children}
      </body>
    </html>
  );
};
export default RootLayout;
